version: '3.8'
services:
  postgres:
    image: postgres:12.3-alpine
    volumes:
      - ./database/development:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    network_mode: "bridge"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
